# vim ft=yaml
language: python

cache: pip

env:
  global:
    - DEPENDS="requirements.txt"
    - COVERAGE=1

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - source tools/travis_tools.sh
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version
  - pip install --upgrade pip
  - wheelhouse_pip_r_install ${DEPENDS}

install:
  - python setup.py install

script:
  - make coverage
  - pip install -r requirements/doc.txt
  - cd doc && make html && cd ..
  - cd doc && make doctest && cd ..

after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
